package org.jikesrvm.replay.tracefile;

/**
 * A chunk is the structural unit of the trace files generated by the replay
 * subsystem.
 * <p>
 * Each trace file chunk contains an header followed by arbritary data.
 */
public interface Chunk {

  /**
   * Gets the total size of the chunk, including the header.
   * @return total size of the chunk
   */
  int getTotalSize();

  /**
   * Gets the size of the chunk, not counting the header.
   * @return size of the chunk
   */
  int getChunkSize();

  /**
   * Gets the header of the chunk.
   * @return header of the chunk
   */
  ChunkHeader getHeader();
}
